# run: conda-env-mod create --file environment.yml --jupyter
name: wav2letter_env
channels: 
  - pytorch
  - conda-forge
dependencies:
  - pytorch #=1.9.0
  - torchaudio #=0.9.0
  - pytorch-lightning #=1.6.0
  - pysoundfile
  - pandas=1.4.2

  - pillow
  - tensorboard